# Generated by Django 4.0.6 on 2023-07-31 09:20

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.BigIntegerField(validators=[contacts.models.validate_mobile_number])),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
